name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 这里填写你存放源码的分支名，通常是 main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # 请根据你本地的 Node 版本修改
      - name: Install Dependencies
        run: npm ci
      - name: Clean and Generate
        run: |
          npm run clean
          npm run build
        # 如果你的 package.json 里没有 clean 和 build 脚本，请替换为 hexo clean 和 hexo generate
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.RRAPHAE1_BLOG_PAGE_PERSONAL_TOKEN }}
          publish_dir: ./public
          publish_branch: page  # 静态文件存放的分支，确保它和你 GitHub Pages 设置的分支一致
          full_commit_message: ${{ github.event.head_commit.message }}
          # external_repository: your-username/your-repo-name  # 替换为你的 GitHub 用户名/仓库名